services:
  db:
    image: postgres:latest
    container_name: lyrics_postgres
    environment:
      - POSTGRES_DB=lyrics_db
      - POSTGRES_USER=jesus
      - POSTGRES_PASSWORD=my_secret_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: